"""V14.2 product signal snapshot service.

Signals are generated by comparing system product snapshots. This keeps the task
signal layer aligned with the product module state shown to users.
"""

from __future__ import annotations

import hashlib
from datetime import datetime
from typing import Any, Dict, List

from src.repositories.sqlite_repository import connect, dumps, ensure_columns, loads
from src.services.system_product_snapshot_service import get_product_snapshot, materialize_system_product_snapshot, previous_product_snapshot

PRODUCT_SIGNAL_SNAPSHOT_VERSION = "14.2.0"
COMPARE_FIELDS = {
    "inventory": "product_inventory_changed",
    "paymentAmount": "product_payment_changed",
    "grossMargin": "product_margin_changed",
    "roi": "product_roi_changed",
    "clickRate": "product_click_changed",
    "conversionRate": "product_conversion_changed",
    "refundRate": "product_refund_changed",
    "adSpend": "product_ad_spend_changed",
    "organicVisitors": "product_organic_changed",
    "paidVisitors": "product_paid_changed",
}


def now_iso() -> str:
    return datetime.now().isoformat()


def ensure_product_signal_tables() -> None:
    with connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS product_signal_snapshots_v14 (
                signal_snapshot_id TEXT PRIMARY KEY,
                data_version TEXT,
                product_snapshot_id TEXT,
                previous_snapshot_id TEXT,
                signal_count INTEGER DEFAULT 0,
                payload TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )
        ensure_columns(conn, "product_signal_snapshots_v14", {"data_version": "TEXT", "product_snapshot_id": "TEXT", "previous_snapshot_id": "TEXT", "signal_count": "INTEGER DEFAULT 0", "updated_at": "TEXT"})
        conn.execute("CREATE INDEX IF NOT EXISTS idx_product_signal_snapshot_v14_version ON product_signal_snapshots_v14(data_version, created_at)")
        conn.commit()


def signal_snapshot_id_for(data_version: str | None) -> str:
    return f"PRODUCT-SIGNAL-SNAPSHOT-{data_version or 'latest'}"


def _text(value: Any) -> str:
    return str(value or "").strip()


def _num(value: Any) -> float | None:
    if value in {None, "", "—", "未识别"}:
        return None
    try:
        return float(str(value).replace("¥", "").replace(",", "").replace("%", "").strip())
    except Exception:
        return None


def _change(old: Any, new: Any) -> float | None:
    old_num = _num(old)
    new_num = _num(new)
    if old_num is None or new_num is None or abs(old_num) < 1e-9:
        return None
    return (new_num - old_num) / abs(old_num)


def _strength(field: str, old: Any, new: Any, change_rate: float | None) -> str:
    new_num = _num(new)
    if field == "inventory" and new_num is not None and new_num <= 0:
        return "high"
    if field == "refundRate" and new_num is not None and new_num >= 12:
        return "high"
    if change_rate is not None and abs(change_rate) >= 0.25:
        return "medium"
    if _text(old) != _text(new):
        return "low"
    return "none"


def _signal_id(seed: str) -> str:
    return "PSIG-" + hashlib.sha1(seed.encode("utf-8")).hexdigest()[:14].upper()


def _index_products(snapshot: Dict[str, Any] | None) -> Dict[str, Dict[str, Any]]:
    products = (snapshot or {}).get("products") or []
    return {str(item.get("objectId") or f"{item.get('storeId') or 'GLOBAL'}::{item.get('productId')}"): item for item in products if item.get("productId") or item.get("objectId")}


def _build_signals(current: Dict[str, Any], previous: Dict[str, Any] | None) -> List[Dict[str, Any]]:
    data_version = current.get("dataVersion")
    current_products = _index_products(current)
    previous_products = _index_products(previous)
    signals: List[Dict[str, Any]] = []
    for key, item in current_products.items():
        old = previous_products.get(key)
        if not old:
            seed = f"{data_version}|{key}|product_newly_seen"
            signals.append({"signalId": _signal_id(seed), "dataVersion": data_version, "entityType": "product", "entityId": item.get("objectId") or key, "productId": item.get("productId"), "storeId": item.get("storeId"), "signalType": "product_newly_seen", "signalStrength": "low", "metricCode": "product_snapshot", "currentValue": item.get("title"), "previousValue": None, "changeRate": None, "productSnapshot": item, "previousProductSnapshot": None})
            continue
        for field, signal_type in COMPARE_FIELDS.items():
            old_value = old.get(field)
            new_value = item.get(field)
            if _text(old_value) == _text(new_value):
                continue
            change_rate = _change(old_value, new_value)
            strength = _strength(field, old_value, new_value, change_rate)
            if strength == "none":
                continue
            seed = f"{data_version}|{key}|{field}|{old_value}|{new_value}"
            signals.append({"signalId": _signal_id(seed), "dataVersion": data_version, "entityType": "product", "entityId": item.get("objectId") or key, "productId": item.get("productId"), "storeId": item.get("storeId"), "signalType": signal_type, "signalStrength": strength, "metricCode": field, "previousValue": old_value, "currentValue": new_value, "changeRate": change_rate, "productSnapshot": item, "previousProductSnapshot": old})
    for key, old in previous_products.items():
        if key in current_products:
            continue
        seed = f"{data_version}|{key}|product_missing_from_latest"
        signals.append({"signalId": _signal_id(seed), "dataVersion": data_version, "entityType": "product", "entityId": old.get("objectId") or key, "productId": old.get("productId"), "storeId": old.get("storeId"), "signalType": "product_missing_from_latest", "signalStrength": "medium", "metricCode": "product_presence", "previousValue": old.get("title"), "currentValue": None, "changeRate": None, "productSnapshot": None, "previousProductSnapshot": old})
    return signals


def row_to_signal_snapshot(row: Any) -> Dict[str, Any]:
    payload = loads(row["payload"])
    return {**payload, "signalSnapshotId": row["signal_snapshot_id"], "dataVersion": row["data_version"], "productSnapshotId": row["product_snapshot_id"], "previousSnapshotId": row["previous_snapshot_id"], "signalCount": int(row["signal_count"] or 0), "createdAt": row["created_at"], "updatedAt": row["updated_at"]}


def get_product_signal_snapshot(data_version: str | None = None) -> Dict[str, Any] | None:
    ensure_product_signal_tables()
    with connect() as conn:
        if data_version:
            row = conn.execute("SELECT * FROM product_signal_snapshots_v14 WHERE data_version = ? ORDER BY created_at DESC LIMIT 1", (data_version,)).fetchone()
        else:
            row = conn.execute("SELECT * FROM product_signal_snapshots_v14 ORDER BY created_at DESC LIMIT 1").fetchone()
    return row_to_signal_snapshot(row) if row else None


def materialize_product_signal_snapshot(data_version: str | None = None, *, user_id: str | None = None, force: bool = True) -> Dict[str, Any]:
    ensure_product_signal_tables()
    current = get_product_snapshot(data_version) or materialize_system_product_snapshot(data_version=data_version, user_id=user_id, force=force)
    previous = previous_product_snapshot(data_version)
    signals = _build_signals(current, previous)
    snapshot_id = signal_snapshot_id_for(data_version)
    payload = {"version": PRODUCT_SIGNAL_SNAPSHOT_VERSION, "signalSnapshotId": snapshot_id, "dataVersion": data_version, "stationId": "product_signal_snapshot_station", "productSnapshotId": current.get("snapshotId"), "previousSnapshotId": previous.get("snapshotId") if previous else None, "productSnapshotCount": current.get("productCount") or len(current.get("products") or []), "productSignalCount": len(signals), "signals": signals, "rule": "V14.2 product signals are generated from system product snapshot comparison."}
    now = now_iso()
    with connect() as conn:
        conn.execute(
            """
            INSERT OR REPLACE INTO product_signal_snapshots_v14 (signal_snapshot_id, data_version, product_snapshot_id, previous_snapshot_id, signal_count, payload, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, COALESCE((SELECT created_at FROM product_signal_snapshots_v14 WHERE signal_snapshot_id = ?), ?), ?)
            """,
            (snapshot_id, data_version, payload["productSnapshotId"], payload["previousSnapshotId"], len(signals), dumps(payload), snapshot_id, now, now),
        )
        conn.commit()
        row = conn.execute("SELECT * FROM product_signal_snapshots_v14 WHERE signal_snapshot_id = ?", (snapshot_id,)).fetchone()
    return {**row_to_signal_snapshot(row), "outputRef": f"product_signal_snapshot:{snapshot_id}", "productSignalSnapshotRef": f"product_signal_snapshot:{snapshot_id}"}


def product_signal_snapshot_summary(limit: int = 20) -> Dict[str, Any]:
    ensure_product_signal_tables()
    with connect() as conn:
        rows = conn.execute("SELECT * FROM product_signal_snapshots_v14 ORDER BY created_at DESC LIMIT ?", (limit,)).fetchall()
    items = [row_to_signal_snapshot(row) for row in rows]
    return {"version": PRODUCT_SIGNAL_SNAPSHOT_VERSION, "snapshotCount": len(items), "latest": items[0] if items else None, "items": items}
