(function () {
  const s = (value) => AppShell.escape(value);
  const money = (v) => `¥${Number(v || 0).toLocaleString("zh-CN")}`;
  const tasks = () => window.AppTaskStore?.listActiveTasks?.() || [];
  const statusClass = (v) => ["稳定", "在线", "已接收", "正常"].includes(v) ? "good" : ["空闲", "审计中", "待确认"].includes(v) ? "watch" : "warning";
  const stores = [
    { platform: "淘宝", name: "家居生活主店", products: 126, orders: 236, sales: 42800, profit: 9100, comments: 18320, refund: "3.2%", stock: 186000, status: "稳定" },
    { platform: "拼多多", name: "家居百货店", products: 98, orders: 318, sales: 35600, profit: 6200, comments: 24680, refund: "5.8%", stock: 142000, status: "关注" },
    { platform: "抖音小店", name: "家居好物号", products: 64, orders: 152, sales: 29800, profit: 4800, comments: 10560, refund: "6.1%", stock: 98000, status: "关注" },
    { platform: "拼多多", name: "家清收纳店", products: 76, orders: 188, sales: 31200, profit: 5900, comments: 12800, refund: "4.4%", stock: 88000, status: "稳定" },
  ];
  const people = [{ name: "店群总管", role: "总管", state: "待派发", current: 3, done: 0, returned: 0, avg: "12 分", load: 72 }, { name: "运营 A", role: "运营", state: "处理中", current: 2, done: 4, returned: 1, avg: "18 分", load: 64 }, { name: "运营 B", role: "运营", state: "空闲", current: 0, done: 2, returned: 0, avg: "21 分", load: 28 }, { name: "数据财务", role: "财务", state: "在线", current: 1, done: 3, returned: 0, avg: "15 分", load: 45 }];
  const supply = [{ name: "义乌家居源头仓", kind: "收纳", cost: "+2.8%", cycle: "3 天", stock: 186000, safe: "正常", state: "稳定" }, { name: "佛山办公坐垫厂", kind: "坐垫", cost: "+6.4%", cycle: "5 天", stock: 142000, safe: "偏低", state: "关注" }, { name: "台州塑料家居厂", kind: "收纳盒", cost: "-1.2%", cycle: "4 天", stock: 98000, safe: "正常", state: "稳定" }];
  const traffic = [{ platform: "淘宝", spend: 12800, roas: 2.9, cpc: "¥0.82", cv: "4.8%", paid: 86, natural: 150, state: "稳定" }, { platform: "拼多多", spend: 9600, roas: 2.2, cpc: "¥0.64", cv: "5.6%", paid: 128, natural: 190, state: "关注" }, { platform: "抖音小店", spend: 15200, roas: 1.8, cpc: "¥1.12", cv: "3.9%", paid: 74, natural: 78, state: "关注" }];
  const finance = { sales: 139400, gross: 26000, ad: 37600, refund: 7200, logistics: 9600, fee: 4100, inventory: 504000, net: 12700 };
  const retrospectives = [{ type: "日报", period: "今日", owner: "店群总管", scope: "全部店群", target: "日销 130,000", actual: "139,400", rate: "107.2%", issue: "抖音 ROAS 偏低，拼多多退款率抬升", status: "已接收", action: "纳入周复盘观察", details: ["今日销售达标。", "抖音小店 ROAS 低于目标。", "拼多多退款率需要继续压降。"], agentPlan: ["检索投流消耗、退款订单和差评商品。", "判断异常是否连续出现。"] }];
  const auditIssues = [{ issue: "投流 ROI 不达标", source: "专项复盘", level: "高", owner: "运营 B", reason: "抖音 ROAS 1.8", action: "降低低转化预算", status: "待处理", evidence: ["抖音 ROAS 连续低于目标。"], agentChecks: ["检索商品级广告消耗。"] }];
  const nextTasks = [{ cycle: "下周", task: "抖音低 ROAS 商品预算收缩", owner: "店群总管", split: ["运营 B 复查低 ROAS 商品。", "数据财务复核 ROI 和广告消耗。"], priority: "高", status: "待下发", source: "本周周报 + 专项复盘", goal: "降低低效投流消耗。" }];
  const total = (arr, key) => arr.reduce((n, x) => n + Number(x[key] || 0), 0);
  const hero = (code, title, desc, label, value) => `<section class="report-hero realtime-hero"><div><p class="eyebrow">${s(code)}</p><h2>${s(title)}</h2><p>${s(desc)}</p></div><div class="report-hero-side"><span>${s(label)}</span><strong>${s(value)}</strong><small>经营单元权限层</small></div></section>`;
  const metrics = (items) => `<section class="kpi-grid report-metrics realtime-metrics">${items.map(([a, b, c]) => `<article class="card realtime-metric"><h3>${s(a)}</h3><strong>${s(b)}</strong><small>${s(c)}</small></article>`).join("")}</section>`;
  const cards = (title, badge, items) => `<section class="page-section realtime-section"><div class="section-header"><h3>${s(title)}</h3><span class="status-badge">${s(badge)}</span></div><div class="supply-grid">${items.map((x) => `<article class="chain-card"><header><div><span class="status-dot ${statusClass(x.state || x.status)}"></span><strong>${s(x.title)}</strong></div><span class="status-badge">${s(x.badge)}</span></header><p>${s(x.text)}</p><footer>${s(x.footer || x.state || x.status || "同步")}</footer></article>`).join("")}</div></section>`;
  const table = (title, head, rows) => `<section class="page-section realtime-section"><div class="section-header"><h3>${s(title)}</h3><span class="status-badge">TABLE</span></div><div class="store-table"><div class="finance-table-row head">${head.map((x) => `<span>${s(x)}</span>`).join("")}</div>${rows.map((row) => `<div class="finance-table-row">${row.map((x, i) => i ? `<span>${s(x)}</span>` : `<strong>${s(x)}</strong>`).join("")}</div>`).join("")}</div></section>`;
  const pills = (items) => `<div class="review-pill-row">${items.map((item) => `<span>${s(item)}</span>`).join("")}</div>`;
  const detailList = (title, items) => `<div class="review-detail-block"><strong>${s(title)}</strong><ul>${items.map((item) => `<li>${s(item)}</li>`).join("")}</ul></div>`;
  function storeNames(user, storeList) { const map = new Map((storeList || []).map((item) => [item.id, item.name])); return (user.storeIds || []).map((id) => map.get(id) || id).join(" / ") || "未授权店铺"; }
  function orgTree(account) { const users = account?.users || []; const storeList = account?.stores || []; const owner = users.find((u) => u.roleId === "owner") || {}; const manager = users.find((u) => u.roleId === "manager") || {}; const children = users.filter((u) => ["operator", "finance", "observer"].includes(u.roleId)); return `<section class="page-section org-section"><div class="section-header"><h3>职位关系网</h3><span class="status-badge">ORG MAP</span></div><div class="org-map"><article class="org-node owner"><strong>${s(owner.name || "老板")}</strong><span>${s(owner.roleName || "老板账号")}</span><small>全部经营单元 / 店铺责任最终负责人</small></article><div class="org-line"></div><article class="org-node manager"><strong>${s(manager.name || "店群总管")}</strong><span>${s(manager.roleName || "店群总管账号")}</span><small>主管：${s(owner.name || "老板")} · ${s(storeNames(manager, storeList))}</small></article><div class="org-children">${children.map((user) => `<article class="org-node"><strong>${s(user.name)}</strong><span>${s(user.roleName)}</span><small>直属主管：${s(manager.name || "店群总管")} · ${s(storeNames(user, storeList))}</small></article>`).join("")}</div></div></section>`; }
  function orgControls(account) { if (!AppApi.can("manage_roles")) return `<section class="page-section org-section"><h3>账号权限控制</h3><p>当前账号只能查看自己的经营单元和店铺切片，不能调整店铺负责人。</p></section>`; const operators = (account?.users || []).filter((user) => user.roleId === "operator"); const stores = account?.stores || []; const assignmentCards = stores.map((store) => `<article class="org-control-card responsibility-card"><div class="section-header"><div><h3>${s(store.name)}</h3><p>${s(store.platform)} · ${s(store.primaryOperatorName || "未分配运营")}</p></div><span class="status-badge">店铺责任</span></div><div class="assignment-current"><strong>主负责人</strong><span>${s(store.primaryOperatorName || "未分配")}</span><small>复核人：${s(store.reviewerName || "店群总管")}</small></div><div class="permission-chip-row">${operators.map((op) => `<button type="button" class="secondary ${store.primaryOperatorId === op.id ? "active" : ""}" data-store-owner="${s(store.id)}:${s(op.id)}">${store.primaryOperatorId === op.id ? "✓ " : ""}${s(op.name)}</button>`).join("")}</div></article>`).join(""); const userCards = operators.map((user) => `<article class="org-control-card"><div class="section-header"><h3>${s(user.name)}</h3><span class="status-badge">运营切片</span></div><p>负责店铺：${s(storeNames(user, stores))}</p><small>运营能进入共同经营单元，但只看自己负责店铺内的商品、报表、预警和待办。</small></article>`).join(""); return `<section class="page-section org-section"><div class="section-header"><h3>店铺运营责任分配</h3><span class="status-badge">老板可配置</span></div><p class="org-scope-note">经营单元共同可见；店铺负责人决定运营账号的数据切片和任务归属。</p><div class="org-control-grid assignment-grid">${assignmentCards}</div></section><section class="page-section org-section"><div class="section-header"><h3>运营可见范围</h3><span class="status-badge">按店铺过滤</span></div><div class="org-control-grid">${userCards}</div></section>`; }
  function orgAlerts(account) { const unassigned = (account?.stores || []).filter((store) => !store.primaryOperatorId).length; return cards("组织配置观察", "GOVERNANCE", [{ title: "经营单元边界", badge: "已拆分", state: "稳定", text: "经营单元是共同业务空间，店铺权限是运营责任边界。" }, { title: "店铺负责人", badge: unassigned ? "关注" : "正常", state: unassigned ? "关注" : "稳定", text: unassigned ? `${unassigned} 家店铺没有主负责人。` : "所有店铺都已配置主负责人。" }, { title: "任务归属", badge: "按店铺", state: "稳定", text: "商品、流量、上新和预警任务会继承店铺责任权限。" }]); }
  function retrospectivePanels() { return `<section class="page-section review-section"><div class="section-header"><h3>周期复盘接收</h3><span class="status-badge">可展开</span></div><div class="review-card-list">${retrospectives.map((item) => `<details class="review-card"><summary><div><span class="status-dot ${statusClass(item.status)}"></span><strong>${s(item.type)} · ${s(item.period)}</strong><small>${s(item.owner)} · ${s(item.scope)}</small></div><div class="review-summary-meta"><span>${s(item.status)}</span><b>${s(item.rate)}</b></div></summary><div class="review-detail">${pills([`目标 ${item.target}`, `实际 ${item.actual}`, item.action])}${detailList("复盘要点", item.details)}${detailList("Agent 预留判断", item.agentPlan)}</div></details>`).join("")}</div></section>`; }
  function auditPanels() { return `<section class="page-section review-section"><div class="section-header"><h3>审计问题清单</h3><span class="status-badge">可展开</span></div><div class="review-card-list">${auditIssues.map((item) => `<details class="review-card"><summary><div><span class="status-dot ${statusClass(item.status)}"></span><strong>${s(item.issue)}</strong><small>${s(item.source)} · 负责人：${s(item.owner)}</small></div><div class="review-summary-meta"><span>${s(item.level)}</span><b>${s(item.status)}</b></div></summary><div class="review-detail">${pills([item.reason, item.action, `等级 ${item.level}`])}${detailList("审计证据", item.evidence)}${detailList("Agent 判断项", item.agentChecks)}</div></details>`).join("")}</div></section>`; }
  function taskDraftPanels() { return `<section class="page-section review-section"><div class="section-header"><h3>下周期任务草案</h3><span class="status-badge">可展开</span></div><div class="review-card-list">${nextTasks.map((item) => `<details class="review-card"><summary><div><span class="status-dot ${statusClass(item.status)}"></span><strong>${s(item.cycle)} · ${s(item.task)}</strong><small>${s(item.source)} · 责任主管：${s(item.owner)}</small></div><div class="review-summary-meta"><span>${s(item.priority)}</span><b>${s(item.status)}</b></div></summary><div class="review-detail">${pills([item.goal, `优先级 ${item.priority}`, item.status])}${detailList("拆分方向", item.split)}</div></details>`).join("")}</div></section>`; }
  window.StoreOverviewPage = { route: "store-overview", title: "店群总览", render() { return `${hero("STORE GROUP LIVE BOARD", "店群总览", "老板先看平台、店铺、商品、订单、销售额、利润、评论、退款、库存和待办。", "运营店铺", stores.length)}${metrics([["运营平台", 3, "淘宝 / 拼多多 / 抖音"], ["店铺数量", stores.length, "当前运营中"], ["今日订单", total(stores, "orders"), "实时经营"], ["销售额", money(total(stores, "sales")), "跨平台汇总"], ["利润", money(total(stores, "profit")), "预估毛利"], ["库存金额", money(total(stores, "stock")), "资金占用"], ["待办", tasks().length, "进入闭环"]])}${cards("平台经营", "LIVE", stores.map(x => ({ title: x.platform, badge: x.status, state: x.status, text: `${x.name} · 商品 ${x.products} · 订单 ${x.orders} · 销售额 ${money(x.sales)} · 利润 ${money(x.profit)}` })))}${table("店铺经营明细", ["店铺", "平台", "商品", "订单", "销售额", "利润", "评论", "退款率"], stores.map(x => [x.name, x.platform, x.products, x.orders, money(x.sales), money(x.profit), x.comments, x.refund]))}`; } };
  window.TaskCommandPage = { route: "task-command", title: "人员总览", render() { return `${hero("PEOPLE OVERVIEW", "人员总览", "老板看任务压在谁身上、谁忙、谁空闲、谁被退回、谁可能成为闭环卡点。", "在线人员", people.length)}${metrics([["在线人员", people.length, "总管 / 运营 / 财务"], ["忙碌人员", people.filter(x => x.load >= 60).length, "关注负荷"], ["空闲人员", people.filter(x => x.state === "空闲").length, "可承接任务"], ["今日完成", total(people, "done"), "团队产出"], ["退回", total(people, "returned"), "质量观察"], ["任务池", tasks().length, "待闭环"]])}${cards("员工实时状态", "LIVE", people.map(x => ({ title: x.name, badge: x.state, state: x.state, text: `${x.role} · 当前 ${x.current} · 完成 ${x.done} · 退回 ${x.returned} · 负荷 ${x.load}%` })))}${table("人员任务映射", ["人员", "角色", "状态", "当前", "完成", "退回", "平均", "负荷"], people.map(x => [x.name, x.role, x.state, x.current, x.done, x.returned, x.avg, `${x.load}%`]))}`; } };
  window.ProfitBudgetPage = { route: "profit-budget", title: "供投财务", render() { return `${hero("SUPPLY · TRAFFIC · FINANCE", "供投财务", "老板在这里看货、流量、钱三条链路。", "净利润", money(finance.net))}${metrics([["供应商", supply.length, "核心供货"], ["库存金额", money(total(supply, "stock")), "供货资金"], ["广告消耗", money(total(traffic, "spend")), "今日投放"], ["综合 ROAS", "2.2", "付费回收"], ["毛利", money(finance.gross), "今日汇总"], ["退款成本", money(finance.refund), "售后吞利"]])}${cards("货 · 流量 · 钱", "CHAIN", [{ title: "供货", badge: `${supply.length} 家`, state: "关注", text: `库存 ${money(total(supply, "stock"))} · 平均供货 4 天` }, { title: "投放", badge: `${traffic.length} 平台`, state: "关注", text: `消耗 ${money(total(traffic, "spend"))} · ROAS 2.2` }, { title: "财务", badge: "今日", state: "稳定", text: `销售额 ${money(finance.sales)} · 净利润 ${money(finance.net)}` }])}${table("供应链看板", ["供应商", "品类", "成本变化", "供货周期", "库存", "安全库存", "状态"], supply.map(x => [x.name, x.kind, x.cost, x.cycle, money(x.stock), x.safe, x.state]))}`; } };
  window.OrgEfficiencyPage = { route: "org-efficiency", title: "组织效率", async render() { const account = await AppApi.accounts(); const users = account?.users || []; return `${hero("ORG PERMISSION NETWORK", "组织效率", "这里配置经营单元、店铺负责人、账号权限和角色模板。", "员工总数", users.length)}${metrics([["员工总数", users.length, "全部账号"], ["主管人数", users.filter(x => x.roleId === "manager").length, "管理层"], ["运营人数", users.filter(x => x.roleId === "operator").length, "执行层"], ["店铺责任", (account?.stores || []).length, "可配置"], ["权限变更", (account?.roleChangeLogs || []).length, "审计记录"]])}${orgTree(account)}${orgControls(account)}${orgAlerts(account)}`; }, mount(ctx) { ctx.delegate("[data-store-owner]", "click", async (_, node) => { const [storeId, operatorId] = node.dataset.storeOwner.split(":"); await AppApi.updateStoreAssignment(storeId, operatorId); await AppApi.prefetch(); AppRouter.schedule("org-store-owner"); }); } };
  window.ReviewAuditPage = { route: "review-audit", title: "复盘审计", render() { return `${hero("RETROSPECTIVE AUDIT", "复盘审计", "接收日报、周报、月报和专项复盘，审查运行失误点，并形成下周期任务草案。", "待生成任务", nextTasks.length)}${metrics([["今日日报", 1, "已接收"], ["审计异常", auditIssues.length, "待处理"], ["待生成任务", nextTasks.length, "下周期"]])}${retrospectivePanels()}${auditPanels()}${taskDraftPanels()}`; } };
})();
