(function () {
  const s = (value) => AppShell.escape(value);
  const stores = [
    { platform: "淘宝", name: "家居生活主店", products: 126, orders: 236, sales: 42800, profit: 9100, comments: 18320, refund: "3.2%", stock: 186000, status: "稳定" },
    { platform: "拼多多", name: "家居百货店", products: 98, orders: 318, sales: 35600, profit: 6200, comments: 24680, refund: "5.8%", stock: 142000, status: "关注" },
    { platform: "抖音小店", name: "家居好物号", products: 64, orders: 152, sales: 29800, profit: 4800, comments: 10560, refund: "6.1%", stock: 98000, status: "关注" },
  ];
  const people = [
    { name: "店群总管", role: "总管", state: "待派发", current: 3, done: 0, returned: 0, avg: "12 分", load: 72, action: "6 分钟前查看任务池" },
    { name: "运营 A", role: "运营", state: "处理中", current: 2, done: 4, returned: 1, avg: "18 分", load: 64, action: "3 分钟前提交处理结果" },
    { name: "运营 B", role: "运营", state: "空闲", current: 0, done: 2, returned: 0, avg: "21 分", load: 28, action: "28 分钟前完成任务" },
    { name: "数据财务", role: "财务", state: "在线", current: 1, done: 3, returned: 0, avg: "15 分", load: 45, action: "9 分钟前补充财务口径" },
  ];
  const supply = [
    { name: "义乌家居源头仓", kind: "收纳", cost: "+2.8%", cycle: "3 天", stock: 186000, safe: "正常", state: "稳定" },
    { name: "佛山办公坐垫厂", kind: "坐垫", cost: "+6.4%", cycle: "5 天", stock: 142000, safe: "偏低", state: "关注" },
    { name: "台州塑料家居厂", kind: "收纳盒", cost: "-1.2%", cycle: "4 天", stock: 98000, safe: "正常", state: "稳定" },
  ];
  const traffic = [
    { platform: "淘宝", spend: 12800, roas: 2.9, cpc: "¥0.82", cv: "4.8%", paid: 86, natural: 150, state: "稳定" },
    { platform: "拼多多", spend: 9600, roas: 2.2, cpc: "¥0.64", cv: "5.6%", paid: 128, natural: 190, state: "关注" },
    { platform: "抖音小店", spend: 15200, roas: 1.8, cpc: "¥1.12", cv: "3.9%", paid: 74, natural: 78, state: "关注" },
  ];
  const finance = { sales: 108200, gross: 20100, ad: 37600, refund: 7200, logistics: 9600, fee: 4100, inventory: 426000, net: 6800 };
  const tasks = () => window.AppTaskStore?.listActiveTasks?.() || [];
  const logs = () => window.AppTaskStore?.listLogs?.() || [];
  const money = (v) => `¥${Number(v || 0).toLocaleString("zh-CN")}`;
  const total = (arr, key) => arr.reduce((n, x) => n + Number(x[key] || 0), 0);
  const statusClass = (v) => v === "稳定" || v === "在线" ? "good" : v === "空闲" ? "watch" : "warning";
  const hero = (code, title, desc, label, value) => `<section class="report-hero realtime-hero"><div><p class="eyebrow">${s(code)}</p><h2>${s(title)}</h2><p>${s(desc)}</p></div><div class="report-hero-side"><span>${s(label)}</span><strong>${s(value)}</strong><small>老板统筹层</small></div></section>`;
  const metrics = (items) => `<section class="kpi-grid report-metrics realtime-metrics">${items.map(([a,b,c]) => `<article class="card realtime-metric"><h3>${s(a)}</h3><strong>${s(b)}</strong><small>${s(c)}</small></article>`).join("")}</section>`;
  const cards = (title, badge, items) => `<section class="page-section realtime-section"><div class="section-header"><h3>${s(title)}</h3><span class="status-badge">${s(badge)}</span></div><div class="supply-grid">${items.map((x) => `<article class="chain-card"><header><div><span class="status-dot ${statusClass(x.state)}"></span><strong>${s(x.title)}</strong></div><span class="status-badge">${s(x.badge)}</span></header><p>${s(x.text)}</p><footer>${s(x.state || "同步")} · ${new Date().toLocaleTimeString("zh-CN", { hour12: false })}</footer></article>`).join("")}</div></section>`;
  const table = (title, head, rows) => `<section class="page-section realtime-section"><div class="section-header"><h3>${s(title)}</h3><span class="status-badge">TABLE</span></div><div class="store-table"><div class="finance-table-row head">${head.map((x) => `<span>${s(x)}</span>`).join("")}</div>${rows.map((row) => `<div class="finance-table-row">${row.map((x, i) => i ? `<span>${s(x)}</span>` : `<strong>${s(x)}</strong>`).join("")}</div>`).join("")}</div></section>`;

  window.StoreOverviewPage = { route: "store-overview", title: "店群总览", render() { return `${hero("STORE GROUP LIVE BOARD", "店群总览", "老板先看平台、店铺、商品、订单、销售额、利润、评论、退款、库存和待办。", "运营店铺", stores.length)}${metrics([["运营平台", 3, "淘宝 / 拼多多 / 抖音"], ["店铺数量", stores.length, "当前运营中"], ["今日订单", total(stores, "orders"), "实时经营"], ["销售额", money(total(stores, "sales")), "跨平台汇总"], ["利润", money(total(stores, "profit")), "预估毛利"], ["评论", total(stores, "comments").toLocaleString("zh-CN"), "口碑资产"], ["库存金额", money(total(stores, "stock")), "资金占用"], ["待办", tasks().length, "进入闭环"]])}${cards("平台经营", "LIVE", stores.map(x => ({ title: x.platform, badge: x.status, state: x.status, text: `${x.name} · 商品 ${x.products} · 订单 ${x.orders} · 销售额 ${money(x.sales)} · 利润 ${money(x.profit)}` })))}${table("店铺经营明细", ["店铺", "平台", "商品", "订单", "销售额", "利润", "评论", "退款率"], stores.map(x => [x.name, x.platform, x.products, x.orders, money(x.sales), money(x.profit), x.comments, x.refund]))}`; } };
  window.TaskCommandPage = { route: "task-command", title: "人员总览", render() { return `${hero("PEOPLE OVERVIEW", "人员总览", "老板看任务压在谁身上、谁忙、谁空闲、谁被退回、谁可能成为闭环卡点。", "在线人员", people.length)}${metrics([["在线人员", people.length, "总管 / 运营 / 财务"], ["忙碌人员", people.filter(x => x.load >= 60).length, "关注负荷"], ["空闲人员", people.filter(x => x.state === "空闲").length, "可承接任务"], ["今日完成", total(people, "done"), "团队产出"], ["退回", total(people, "returned"), "质量观察"], ["平均处理", "16 分", "团队均值"], ["待派发", 3, "总管处理"], ["任务池", tasks().length, "待闭环"]])}${cards("员工实时状态", "LIVE", people.map(x => ({ title: x.name, badge: x.state, state: x.state, text: `${x.role} · 当前 ${x.current} · 完成 ${x.done} · 退回 ${x.returned} · 负荷 ${x.load}% · ${x.action}` })))}${table("人员任务映射", ["人员", "角色", "状态", "当前", "完成", "退回", "平均", "负荷"], people.map(x => [x.name, x.role, x.state, x.current, x.done, x.returned, x.avg, `${x.load}%`]))}`; } };
  window.ProfitBudgetPage = { route: "profit-budget", title: "供投财务", render() { return `${hero("SUPPLY · TRAFFIC · FINANCE", "供投财务", "老板在这里看货、流量、钱三条链路：供货是否稳定、投流是否划算、财务结果是否健康。", "净利润", money(finance.net))}${metrics([["供应商", supply.length, "核心供货"], ["库存金额", money(total(supply, "stock")), "供货资金"], ["供货周期", "4 天", "平均周期"], ["广告消耗", money(total(traffic, "spend")), "今日投放"], ["综合 ROAS", "2.2", "付费回收"], ["毛利", money(finance.gross), "今日汇总"], ["退款成本", money(finance.refund), "售后吞利"], ["现金压力", "中", "库存 + 投放"]])}${cards("货 · 流量 · 钱", "CHAIN", [{ title: "供货", badge: `${supply.length} 家`, state: "关注", text: `库存 ${money(total(supply, "stock"))} · 平均供货 4 天 · 1 家成本上浮` }, { title: "投放", badge: `${traffic.length} 平台`, state: "关注", text: `消耗 ${money(total(traffic, "spend"))} · ROAS 2.2 · 低效消耗需关注` }, { title: "财务", badge: "今日", state: "稳定", text: `销售额 ${money(finance.sales)} · 毛利 ${money(finance.gross)} · 净利润 ${money(finance.net)}` }])}${table("供应链看板", ["供应商", "品类", "成本变化", "供货周期", "库存", "安全库存", "状态", ""], supply.map(x => [x.name, x.kind, x.cost, x.cycle, money(x.stock), x.safe, x.state, ""]))}${table("投流看板", ["平台", "消耗", "ROAS", "点击成本", "转化率", "付费订单", "自然订单", "状态"], traffic.map(x => [x.platform, money(x.spend), x.roas, x.cpc, x.cv, x.paid, x.natural, x.state]))}${table("财务汇总", ["销售额", "毛利", "广告费", "退款", "物流", "扣点", "库存资金", "净利润"], [[money(finance.sales), money(finance.gross), money(finance.ad), money(finance.refund), money(finance.logistics), money(finance.fee), money(finance.inventory), money(finance.net)]])}`; } };
  window.OrgEfficiencyPage = { route: "org-efficiency", title: "组织效率", render() { const active = tasks(); return `${hero("ORG EFFICIENCY", "组织效率", "这里聚合派发、提交、复核和返工，判断组织是否能闭环。", "任务池", active.length)}${metrics([["已派发", active.filter(x => x.assigneeId).length, "责任已落位"], ["未派发", active.filter(x => !x.assigneeId).length, "需要拆分"], ["待复核", active.filter(x => x.status === "待复核").length, "管理卡点"], ["退回中", active.filter(x => x.workflowStatus === "已退回").length, "质量问题"]])}`; } };
  window.ReviewAuditPage = { route: "review-audit", title: "复核审计", render() { return `${hero("REVIEW AUDIT", "复核审计", "保留派发、提交、复核和归档痕迹，用来回看责任链和经营判断。", "日志", logs().length)}${metrics([["日志记录", logs().length, "可追溯"], ["任务归档", logs().filter(x => String(x.status).includes("完成") || String(x.status).includes("归档")).length, "闭环"], ["派发记录", logs().filter(x => String(x.type).includes("派发")).length, "责任链"], ["复核记录", logs().filter(x => String(x.type).includes("复核")).length, "管理审计"]])}`; } };
})();
