(function () {
  const ACCOUNT_KEY = "ai_ecommerce_v442_current_user_id";
  const status = { source: "unknown", failures: [] };
  let account = null;

  function getCurrentUserId() { return localStorage.getItem(ACCOUNT_KEY) || "U001"; }
  function setCurrentUserId(userId) { localStorage.setItem(ACCOUNT_KEY, userId || "U001"); }
  function currentUser() { return account?.currentUser || null; }
  function currentPermissions() { return currentUser()?.permissions || []; }
  function can(permission) { return currentPermissions().includes(permission); }
  function failureSummary() { if (!status.failures.length) return "所有模块接口请求正常。"; return status.failures.slice(-5).map((item) => `${item.path}: ${item.message}`).join("\n"); }
  async function request(path, fallback, options = {}) {
    try {
      const response = await fetch(path, { method: options.method || "GET", headers: { Accept: "application/json", "Content-Type": "application/json", "X-Mock-User-Id": getCurrentUserId() }, body: options.body ? JSON.stringify(options.body) : undefined });
      if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
      if (status.source !== "fallback") status.source = "server";
      return await response.json();
    } catch (error) { status.source = "fallback"; status.failures.push({ path, message: error.message, at: Date.now() }); console.warn(`[api-client] fallback for ${path}`, error); return fallback; }
  }
  async function loadAccount() { account = await request("/api/accounts", account); return account; }
  async function applyAccountMutation(path, body) { const result = await request(path, null, { method: "POST", body }); account = result?.account || (await loadAccount()); window.dispatchEvent(new CustomEvent("mock-account-change", { detail: { account } })); return result; }
  function applyRecapData(recap) { window.AppMockData.recapCandidates = Array.isArray(recap?.items) ? recap.items : []; window.AppMockData.recapSummary = recap?.summary || { total: 0, daily: 0, weekly: 0, monthly: 0, highRisk: 0 }; }
  const api = {
    status, failureSummary, getCurrentUserId, setCurrentUserId, currentUser, currentPermissions, can,
    dashboard: () => request("/api/modules/dashboard", null), operatingUnit: () => request("/api/modules/operating-unit", null), accounts: loadAccount, me: () => request("/api/accounts/me", null),
    switchAccount: async (userId) => { setCurrentUserId(userId); const switched = await request("/api/accounts/switch", null, { method: "POST", body: { userId } }); account = switched?.account || (await loadAccount()); window.dispatchEvent(new CustomEvent("mock-account-change", { detail: { account } })); return account; },
    updateUserRole: (userId, roleId) => applyAccountMutation(`/api/accounts/users/${encodeURIComponent(userId)}/role`, { roleId }), updateUserStores: (userId, storeIds) => applyAccountMutation(`/api/accounts/users/${encodeURIComponent(userId)}/stores`, { storeIds }), updateStoreAssignment: (storeId, primaryOperatorId, reviewerId = "U002") => applyAccountMutation(`/api/accounts/store-assignments/${encodeURIComponent(storeId)}`, { primaryOperatorId, reviewerId }), updateRolePermissions: (roleId, permissions) => applyAccountMutation(`/api/accounts/roles/${encodeURIComponent(roleId)}/permissions`, { permissions }),
    product: () => request("/api/modules/product", window.AppMockData.products), competitor: () => request("/api/modules/competitor", window.AppMockData.competitors), listing: () => request("/api/modules/listing", window.AppMockData.listings), traffic: () => request("/api/modules/traffic", window.AppMockData.traffic), report: () => request("/api/modules/report", { reportGroups: window.AppMockData.reportGroups, reportDetails: window.AppMockData.reportDetails, v3: null, recentAlerts: [] }),
    agents: () => request("/api/modules/agents", { version: "4.4.2", agents: [], boundary: "Agent 只生成建议，不直接执行经营动作。" }), moduleAgent: (module, id, mode = "analysis") => request(`/api/modules/agents/${encodeURIComponent(module)}/${encodeURIComponent(id)}?mode=${encodeURIComponent(mode)}`, null), cycleAgent: (target = "日报") => request(`/api/modules/agents/cycle/${encodeURIComponent(target)}`, null), createAgentTask: (module, id, draftIndex = 0, mode = "analysis") => api.post(`/api/modules/agents/${encodeURIComponent(module)}/${encodeURIComponent(id)}/tasks`, null, { draftIndex, mode }), generateTaskCandidates: (body = {}) => api.post("/api/modules/agents/tasks/generate", { candidates: [] }, body), taskPlaybook: (taskId, preferredStyle = "") => request(`/api/modules/agents/tasks/${encodeURIComponent(taskId)}/playbook${preferredStyle ? `?preferred_style=${encodeURIComponent(preferredStyle)}` : ""}`, null), creativeAgent: (productId, body = {}) => api.post(`/api/modules/agents/creative/${encodeURIComponent(productId)}`, null, body), createCreativeTask: (productId, body = {}) => api.post(`/api/modules/agents/creative/${encodeURIComponent(productId)}/tasks`, null, body), feedbackFlywheel: () => request("/api/modules/feedback-flywheel", { version: "4.4.2", learningCandidates: [] }), feedbackCycle: (target = "日报", limit = 8) => request(`/api/modules/feedback-flywheel/cycle/${encodeURIComponent(target)}?limit=${encodeURIComponent(limit)}`, null), draftFeedbackCycle: (target = "日报", body = {}) => api.post(`/api/modules/feedback-flywheel/cycle/${encodeURIComponent(target)}/draft`, null, body),
    ragMemory: () => request("/api/modules/rag-memory", { version: "4.4.2", total: 0, approved: 0, pendingReview: 0 }), ragCases: (params = {}) => { const query = new URLSearchParams(); if (params.status) query.set("status", params.status); if (params.level) query.set("level", params.level); if (params.limit) query.set("limit", params.limit); return request(`/api/modules/rag-memory/cases${query.toString() ? `?${query.toString()}` : ""}`, { items: [] }); }, ragSearch: (params = {}) => { const query = new URLSearchParams(); Object.entries(params || {}).forEach(([key, value]) => { if (value !== undefined && value !== null && value !== "") query.set(key, value); }); return request(`/api/modules/rag-memory/search${query.toString() ? `?${query.toString()}` : ""}`, { items: [] }); }, draftTaskMemory: (taskId, body = {}) => api.post(`/api/modules/rag-memory/feedback/tasks/${encodeURIComponent(taskId)}`, null, body), approveRagCase: (caseId, body = {}) => api.post(`/api/modules/rag-memory/cases/${encodeURIComponent(caseId)}/approve`, null, body), rejectRagCase: (caseId, body = {}) => api.post(`/api/modules/rag-memory/cases/${encodeURIComponent(caseId)}/reject`, null, body),
    v3Summary: () => request("/api/data/v3-summary", { version: "4.4.2", activeAlertCount: 0, latestAlerts: [] }), v3Alerts: () => request("/api/data/alerts?active_only=true", []), reportTemplates: () => request("/api/data/templates", { version: "4.4.2", datasets: [] }), previewReportRows: (datasetName, rows, fieldMapping = {}) => api.post("/api/data/preview", null, { datasetName, rows, fieldMapping }), confirmReportImport: (datasetName, rows, fieldMapping = {}) => api.post("/api/data/import/confirm", null, { datasetName, rows, fieldMapping, autoCreateTasks: true }), importMockAlerts: () => api.post("/api/data/import/mock-alerts", null, {}), importReportRows: (datasetName, rows) => api.post("/api/data/import/report", null, { datasetName, rows, autoCreateTasks: true }),
    todo: (params = {}) => { const query = new URLSearchParams(); if (params.scope) query.set("scope", params.scope); if (params.assigneeId) query.set("assignee_id", params.assigneeId); const suffix = query.toString() ? `?${query.toString()}` : ""; return request(`/api/modules/todo${suffix}`, { tasks: window.AppTaskStore?.listTasks?.() || [], activeTasks: window.AppTaskStore?.listActiveTasks?.() || [], events: window.AppTaskStore?.listEvents?.() || [], counters: window.AppTaskStore?.counters?.() || {}, viewer: currentUser() }); },
    todoEvents: () => request("/api/modules/todo/events", { events: window.AppTaskStore?.listEvents?.() || [], counters: window.AppTaskStore?.counters?.() || {}, viewer: currentUser() }),
    todoCounters: () => request("/api/modules/todo/counters", { counters: window.AppTaskStore?.counters?.() || {}, viewer: currentUser() }),
    log: () => request("/api/modules/log", window.AppTaskStore?.listLogs?.() || []), recapCandidates: (target = "") => request(`/api/modules/recap-candidates${target ? `?target=${encodeURIComponent(target)}` : ""}`, { summary: window.AppMockData.recapSummary || {}, items: window.AppMockData.recapCandidates || [] }), taskReport: (id) => request(`/api/modules/task-reports/tasks/${encodeURIComponent(id)}`, null), candidateReport: (module, id) => request(`/api/modules/task-reports/candidates/${encodeURIComponent(module)}/${encodeURIComponent(id)}`, null), alertReport: (id) => request(`/api/modules/task-reports/alerts/${encodeURIComponent(id)}`, null), post: (path, fallback, body) => request(path, fallback, { method: "POST", body }),
    createProductTask: (id) => api.post(`/api/modules/product/${id}/tasks`, null), createCompetitorTask: (id) => api.post(`/api/modules/competitor/${id}/tasks`, null), createListingTask: (id) => api.post(`/api/modules/listing/${id}/tasks`, null), createTrafficTask: (id) => api.post(`/api/modules/traffic/${id}/tasks`, null), createReportTask: (id) => api.post(`/api/modules/report/${id}/tasks`, null),
    splitTodo: (id, body = {}) => api.post(`/api/modules/todo/${id}/split`, null, body), assignTodo: (id, body = {}) => api.post(`/api/modules/todo/${id}/assign`, null, body), acceptTodo: (id, body = {}) => api.post(`/api/modules/todo/${id}/accept`, null, body), submitTodo: (id, body = {}) => api.post(`/api/modules/todo/${id}/submit`, null, body), submitEvidenceTodo: (id, body = {}) => api.post(`/api/modules/todo/${id}/submit-evidence`, null, body), reviewTodo: (id, body = {}) => api.post(`/api/modules/todo/${id}/review`, null, body), reviewEvidenceTodo: (id, body = {}) => api.post(`/api/modules/todo/${id}/review-evidence`, null, body), taskEvidence: (id) => request(`/api/modules/todo/${encodeURIComponent(id)}/evidence`, null), writeRecapTodo: (id, body = {}) => api.post(`/api/modules/todo/${id}/recap`, null, body), completeTodo: (id) => api.post(`/api/modules/todo/${id}/complete`, null), pinTodo: (id) => api.post(`/api/modules/todo/${id}/pin`, null), reorderTodo: (id, direction) => api.post(`/api/modules/todo/${id}/reorder?direction=${encodeURIComponent(direction)}`, null), resetTodo: () => api.post("/api/modules/todo/reset", null),
    applyModuleData({ products, competitors, listings, traffic, report } = {}) { if (Array.isArray(products)) window.AppMockData.products = products; if (Array.isArray(competitors)) window.AppMockData.competitors = competitors; if (Array.isArray(listings)) window.AppMockData.listings = listings; if (Array.isArray(traffic)) window.AppMockData.traffic = traffic; if (report?.reportGroups) window.AppMockData.reportGroups = report.reportGroups; if (report?.reportDetails) window.AppMockData.reportDetails = report.reportDetails; if (report?.v3) window.AppMockData.v3 = report.v3; if (Array.isArray(report?.recentAlerts)) window.AppMockData.recentAlerts = report.recentAlerts; },
    async refreshModuleData() { const [products, competitors, listings, traffic, report] = await Promise.all([api.product(), api.competitor(), api.listing(), api.traffic(), api.report()]); api.applyModuleData({ products, competitors, listings, traffic, report }); return window.AppMockData; },
    async refreshTaskState() { const [todo, logs, recap] = await Promise.all([api.todo(), api.log(), api.recapCandidates()]); applyRecapData(recap); window.AppTaskStore?.hydrate?.(todo?.tasks || [], Array.isArray(logs) ? logs : [], todo?.events || [], todo?.counters || {}); await api.refreshModuleData(); return { todo, logs, recap }; },
    async refreshAfterDataImport() { await api.refreshTaskState(); const summary = await api.v3Summary(); window.AppMockData.v3 = summary; return summary; },
    async prefetch() { await loadAccount(); const [products, competitors, listings, traffic, report, todo, logs, recap] = await Promise.all([api.product(), api.competitor(), api.listing(), api.traffic(), api.report(), api.todo(), api.log(), api.recapCandidates()]); api.applyModuleData({ products, competitors, listings, traffic, report }); applyRecapData(recap); window.AppTaskStore?.hydrate?.(todo?.tasks || [], Array.isArray(logs) ? logs : [], todo?.events || [], todo?.counters || {}); return window.AppMockData; },
  };
  window.AppApi = api;
})();
