"""Data Hub routes."""

from __future__ import annotations

from typing import Any, Dict, List

from fastapi import APIRouter, Body, HTTPException, Query, Request

from src.services.account_service import current_user, user_id_from_headers
from src.services.data_import_service import (
    import_mock_data,
    list_import_records,
    list_import_sources,
    validate_all_imports,
)
from src.services.data_version_service import list_import_records as list_version_import_records
from src.services.data_version_service import rollback_data_version
from src.services.report_alert_service import (
    get_v3_dashboard_summary,
    import_report_dataset,
    latest_data_version,
    list_alert_events,
    list_alerts_for_entity,
    list_data_versions,
    run_v3_mock_imports,
)
from src.services.report_schema_service import (
    confirm_report_import,
    get_report_templates,
    preview_report_dataset,
)

router = APIRouter(prefix="/api/data", tags=["data-import"])
ROLLBACK_ROLE_IDS = {"owner", "manager", "finance"}


def request_user_id(request: Request) -> str:
    return user_id_from_headers(request.headers)


def require_rollback_permission(user_id: str) -> None:
    user = current_user(user_id)
    if user.get("roleId") not in ROLLBACK_ROLE_IDS:
        raise HTTPException(status_code=403, detail="当前账号无权回滚全局数据版本")


@router.get("/sources")
def data_sources() -> List[Dict[str, Any]]:
    """List available Mock ERP / CRM import sources."""
    return list_import_sources()


@router.post("/validate")
def validate_imports() -> Dict[str, Any]:
    """Validate all Mock ERP / CRM datasets and relationship checks."""
    return validate_all_imports()


@router.post("/import/mock")
def import_mock() -> Dict[str, Any]:
    """Create an import record for current Mock datasets after validation."""
    return import_mock_data()


@router.get("/imports")
def imports() -> List[Dict[str, Any]]:
    """List recent import records."""
    return list_import_records()


@router.get("/import-records")
def import_records(limit: int = Query(default=50, ge=1, le=200)) -> Dict[str, Any]:
    """List report data versions with alert/task impact and rollback state."""
    return list_version_import_records(limit=limit)


@router.post("/versions/{data_version}/rollback")
def rollback_version(request: Request, data_version: str, body: Dict[str, Any] | None = Body(default=None)) -> Dict[str, Any]:
    """Soft-rollback alerts generated by one report data version and handle linked tasks."""
    body = body or {}
    user_id = request_user_id(request)
    require_rollback_permission(user_id)
    try:
        return rollback_data_version(
            data_version,
            operator_id=user_id,
            reason=body.get("reason") or body.get("note"),
            task_strategy=body.get("task_strategy") or body.get("taskStrategy") or "review",
        )
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@router.get("/templates")
def report_templates() -> Dict[str, Any]:
    """Return report field templates and alias hints."""
    return get_report_templates()


@router.post("/preview")
def preview_report(body: Dict[str, Any] = Body(default_factory=dict)) -> Dict[str, Any]:
    """Preview field mapping before creating alerts or tasks."""
    dataset_name = body.get("dataset_name") or body.get("datasetName")
    if not dataset_name:
        raise HTTPException(status_code=400, detail="dataset_name is required")
    try:
        return preview_report_dataset(
            str(dataset_name),
            rows=body.get("rows"),
            field_mapping=body.get("field_mapping") or body.get("fieldMapping"),
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@router.post("/import/confirm")
def confirm_import(body: Dict[str, Any] = Body(default_factory=dict)) -> Dict[str, Any]:
    """Confirm a previewed report import, then trigger scoped alerts/tasks."""
    dataset_name = body.get("dataset_name") or body.get("datasetName")
    if not dataset_name:
        raise HTTPException(status_code=400, detail="dataset_name is required")
    try:
        return confirm_report_import(
            str(dataset_name),
            rows=body.get("rows"),
            field_mapping=body.get("field_mapping") or body.get("fieldMapping"),
            auto_create_tasks=body.get("auto_create_tasks", body.get("autoCreateTasks", True)) is not False,
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@router.post("/import/report")
def import_report(body: Dict[str, Any] = Body(default_factory=dict)) -> Dict[str, Any]:
    """Import one report payload, create a data version, then trigger scoped alerts."""
    dataset_name = body.get("dataset_name") or body.get("datasetName")
    if not dataset_name:
        raise HTTPException(status_code=400, detail="dataset_name is required")
    try:
        return import_report_dataset(
            str(dataset_name),
            rows=body.get("rows"),
            auto_create_tasks=body.get("auto_create_tasks", body.get("autoCreateTasks", True)) is not False,
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@router.post("/import/mock-alerts")
def import_mock_alerts(body: Dict[str, Any] = Body(default_factory=dict)) -> Dict[str, Any]:
    """Run report-driven alert generation from current examples/*.csv files."""
    dataset_names = body.get("dataset_names") or body.get("datasetNames")
    try:
        return run_v3_mock_imports(dataset_names=dataset_names)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@router.get("/versions")
def data_versions(limit: int = Query(default=20, ge=1, le=100)) -> List[Dict[str, Any]]:
    """List recent data snapshots created by report imports."""
    return list_data_versions(limit=limit)


@router.get("/versions/latest")
def latest_version() -> Dict[str, Any]:
    """Return the latest data version used by global warning refresh."""
    latest = latest_data_version()
    return latest or {"version": "3.1.3", "message": "No V3 data snapshot has been imported yet."}


@router.get("/alerts")
def alerts(
    request: Request,
    limit: int = Query(default=50, ge=1, le=200),
    active_only: bool = Query(default=False),
) -> List[Dict[str, Any]]:
    """List report-triggered alert events scoped by current account store access."""
    return list_alert_events(limit=limit, active_only=active_only, user_id=request_user_id(request))


@router.get("/alerts/entity/{entity_type}/{entity_id}")
def entity_alerts(request: Request, entity_type: str, entity_id: str) -> List[Dict[str, Any]]:
    """List alert events for one product/customer/entity scoped by current account."""
    return list_alerts_for_entity(entity_type, entity_id, user_id=request_user_id(request))


@router.get("/v3-summary")
def v3_summary(request: Request) -> Dict[str, Any]:
    """Global data-version and alert summary scoped by current account."""
    return get_v3_dashboard_summary(request_user_id(request))
