"""Health routes."""

from __future__ import annotations

from typing import Any, Dict

from fastapi import APIRouter

API_VERSION = "4.1.0"

router = APIRouter(prefix="/api", tags=["health"])


@router.get("/health")
def health() -> Dict[str, Any]:
    return {
        "ok": True,
        "version": API_VERSION,
        "product": "AI ERP Operating Advisor",
        "mode": "v410_rag_memory_flywheel",
        "api_entry": "/api/modules/*",
        "account_entry": "/api/accounts",
        "safety": {
            "auto_scheduled_platform_action": False,
            "auto_ad_account_operation": False,
            "auto_product_publish": False,
            "auto_price_change": False,
            "auto_inventory_change": False,
            "auto_refund": False,
            "auto_erp_crm_write": False,
            "auto_customer_message_blast": False,
            "marketplace_api_connected": False,
        },
        "v4_module_agent_layer": True,
        "v4_agent_version": API_VERSION,
        "agent_runtime_mode": "advisory_only",
        "module_agent_endpoint": "/api/modules/agents/{module}/{entity_id}",
        "module_agent_task_endpoint": "/api/modules/agents/{module}/{entity_id}/tasks",
        "cycle_agent_endpoint": "/api/modules/agents/cycle/{target}",
        "agent_outputs": ["analysis", "summary", "taskDrafts", "humanDecision", "forbiddenActions"],
        "agent_forbidden_actions": ["direct_price_change", "direct_ad_spend_change", "direct_refund", "direct_publish", "direct_erp_crm_write"],
        "agent_requires_human_confirmation": True,
        "v410_rag_memory": True,
        "rag_memory_endpoint": "/api/modules/rag-memory",
        "rag_memory_cases_endpoint": "/api/modules/rag-memory/cases",
        "rag_memory_search_endpoint": "/api/modules/rag-memory/search",
        "rag_memory_feedback_endpoint": "/api/modules/rag-memory/feedback/tasks/{task_id}",
        "rag_memory_approve_endpoint": "/api/modules/rag-memory/cases/{case_id}/approve",
        "rag_memory_reject_endpoint": "/api/modules/rag-memory/cases/{case_id}/reject",
        "rag_memory_write_gate": ["manager_review", "quality_score", "metrics_change", "human_approval"],
        "rag_memory_levels": ["L0 raw/rejected", "L1 draft", "L2 reviewed", "L3 high_quality", "L4 negative_case"],
        "frontend_agent_panel": "task-report",
        "frontend_duplicate_dynamic_loading_removed": True,
        "report_runtime_file": "/web_demo/modules/report/report-runtime.js",
        "manager_modules_file": "/web_demo/modules/manager/manager-modules.js",
        "data_version_service_version": "3.1.4",
        "data_version_detail_endpoint": "/api/data/versions/{data_version}/detail",
        "data_version_detail_backend_payload": True,
        "report_import_records_position": "bottom",
        "report_import_records_compact": True,
        "data_version_detail_route": "data-version-detail",
        "data_version_detail_alerts": True,
        "rollback_permission_roles": ["owner", "manager", "finance"],
        "operator_rollback_hidden": True,
        "import_records_endpoint": "/api/data/import-records",
        "data_version_rollback_endpoint": "/api/data/versions/{data_version}/rollback",
        "data_version_soft_rollback": True,
        "rollback_audit_record": True,
        "rollback_keeps_task_audit": True,
        "rollback_task_strategy": True,
        "rollback_task_strategy_review": True,
        "rollback_task_strategy_archive": True,
        "rollback_task_strategy_keep": True,
        "rollback_task_strategy_default": "review",
        "report_page_rollback_task_strategy_select": "detail_page",
        "inventory_center_endpoint": "/api/modules/inventory",
        "inventory_task_endpoint": "/api/modules/inventory/{product_id}/tasks",
        "customer_service_center_endpoint": "/api/modules/aftersales",
        "customer_service_task_endpoint": "/api/modules/aftersales/{product_id}/tasks",
        "manager_inventory_card_route": "inventory-center",
        "manager_service_card_route": "service-center",
        "operation_center_store_scope": True,
        "operation_center_task_store_owner": True,
        "recap_candidates_endpoint": "/api/modules/recap-candidates",
        "task_approval_to_recap_candidate": True,
        "task_evidence_endpoint": "/api/modules/todo/{task_id}/evidence",
        "task_submit_evidence_endpoint": "/api/modules/todo/{task_id}/submit-evidence",
        "task_review_evidence_endpoint": "/api/modules/todo/{task_id}/review-evidence",
        "alert_evidence_report_endpoint": "/api/modules/task-reports/alerts/{alert_id}",
        "report_row_store_scope": True,
        "report_alerts_scoped_by_account": True,
        "report_preview_store_aliases": True,
        "alert_task_routes_to_store_operator": True,
        "manager_navigation_compacted": True,
        "manager_business_modules_nested": True,
        "minimal_ui_microcopy_removed": True,
        "owner_store_migration_confirm": True,
        "store_permission_next_day_effective": True,
        "role_scoped_task_flow": True,
        "warning_to_operator_todo": True,
        "cross_account_lifecycle_sync": True,
        "v3_data_snapshot": True,
        "v3_report_alert_event": True,
        "v3_alert_to_task_bridge": True,
        "v3_file_first_report_upload": True,
        "v3_report_schema_preview": True,
        "v3_confirm_before_alert": True,
        "v3_templates_endpoint": "/api/data/templates",
        "v3_preview_endpoint": "/api/data/preview",
        "v3_confirm_import_endpoint": "/api/data/import/confirm",
        "v3_alerts_endpoint": "/api/data/alerts",
        "v3_versions_endpoint": "/api/data/versions",
        "v3_summary_endpoint": "/api/data/v3-summary",
    }
